import { useMemo } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useEvent } from '@/hooks/use-events';
import { useGuests } from '@/hooks/use-guests';
import { useTables } from '@/hooks/use-tables';
import { LoadingScreen, ErrorScreen } from '@/components/ui/feedback';

export function PrintSeatingChartPage() {
  const { eventId } = useParams<{ eventId: string }>();
  const { data: event, isLoading: eventLoading } = useEvent(eventId ?? '');
  const { data: tables, isLoading: tablesLoading } = useTables(eventId ?? '');
  const { data: guests, isLoading: guestsLoading } = useGuests(eventId ?? '');

  const guestsByTable = useMemo(() => {
    const map = new Map<string, string[]>();
    for (const g of guests ?? []) {
      if (g.table_id) {
        const arr = map.get(g.table_id) ?? [];
        arr.push(g.name);
        map.set(g.table_id, arr);
      }
    }
    return map;
  }, [guests]);

  const unassigned = useMemo(
    () => (guests ?? []).filter((g) => !g.table_id).map((g) => g.name),
    [guests],
  );

  if (eventLoading || tablesLoading || guestsLoading)
    return <LoadingScreen message="Loading seating chart…" />;
  if (!event) return <ErrorScreen message="Event not found." />;

  const formattedDate = event.date
    ? new Date(event.date).toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      })
    : null;

  const formattedTime = event.time
    ? new Date(`2000-01-01T${event.time}`).toLocaleTimeString('en-US', {
        hour: 'numeric',
        minute: '2-digit',
      })
    : null;

  return (
    <div className="print-page">
      <div className="print-toolbar no-print">
        <Link
          to={`/events/${eventId}/seating`}
          className="btn btn--secondary btn--sm"
        >
          ← Back to Seating
        </Link>
        <div className="flex gap-3">
          <Link
            to={`/events/${eventId}/print/guest-list`}
            className="btn btn--secondary btn--sm"
          >
            Guest List
          </Link>
          <button
            className="btn btn--primary btn--sm"
            onClick={() => window.print()}
          >
            Print / Save as PDF
          </button>
        </div>
      </div>

      <div className="print-document">
        <div className="print-header">
          <h1 className="print-title">{event.name}</h1>
          {event.venue && <p className="print-venue">{event.venue}</p>}
          <p className="print-date">
            {formattedDate}
            {formattedTime && ` · ${formattedTime}`}
          </p>
        </div>

        <h2 className="print-section-title">Seating Chart</h2>

        {tables && tables.length > 0 ? (
          <div className="print-tables-grid">
            {tables.map((table) => {
              const tableGuests = guestsByTable.get(table.id) ?? [];
              return (
                <div key={table.id} className="print-table-card">
                  <div className="print-table-card__header">
                    <span className="print-table-card__name">{table.name}</span>
                    <span className="print-table-card__number">
                      Table {table.number}
                    </span>
                  </div>
                  <div className="print-table-card__count">
                    {tableGuests.length} / {table.capacity} guests
                  </div>
                  <ul className="print-table-card__guests">
                    {tableGuests.length > 0 ? (
                      tableGuests.map((name, i) => (
                        <li key={i} className="print-guest-name">
                          {name}
                        </li>
                      ))
                    ) : (
                      <li className="print-guest-name print-guest-name--empty">
                        No guests assigned
                      </li>
                    )}
                  </ul>
                </div>
              );
            })}
          </div>
        ) : (
          <p className="print-empty">No tables have been created yet.</p>
        )}

        {unassigned.length > 0 && (
          <div className="print-unassigned">
            <h3 className="print-section-title--sub">Unassigned Guests</h3>
            <ul className="print-unassigned-list">
              {unassigned.map((name, i) => (
                <li key={i} className="print-guest-name">
                  {name}
                </li>
              ))}
            </ul>
          </div>
        )}

        <div className="print-footer">
          <p>
            Generated by Seatly ·{' '}
            {new Date().toLocaleDateString('en-US', {
              month: 'long',
              day: 'numeric',
              year: 'numeric',
            })}
          </p>
        </div>
      </div>
    </div>
  );
}
